/**
 * @file components/ai-explanation-panel.tsx
 *
 * Secondary, consent-driven presentation for the existing optional explanation
 * flow. The deterministic local report remains visually and conceptually
 * primary; this component does not make or interpret local findings itself.
 */

"use client";

import { useState } from "react";
import {
  LIVE_AI_UNAVAILABLE_MESSAGE,
  aiExplanationResponseSchema,
  toAiExplanationInput,
  type AiExplanationResponse,
} from "@/lib/ai-explanation-schema";
import type { Analysis, EmailInput } from "@/lib/schemas";

type AiExplanationPanelProps = {
  input: EmailInput;
  analysis: Analysis;
  /** UI hint from a server-verified session; the route remains authoritative. */
  isAdminAuthenticated: boolean;
};

/** Renders result content only after its local, demo, or live source is explicit. */
function ExplanationContent({ result, analysis }: { result: AiExplanationResponse; analysis: Analysis }) {
  if (result.mode === "unavailable") {
    return (
      <div className="ai-unavailable-state" role="status">
        <p>Explanation unavailable</p>
        <p>{result.message}</p>
      </div>
    );
  }

  const isDemo = result.mode === "demo";

  return (
    <div className="ai-result" aria-live="polite">
      <div className={`ai-source-notice ${isDemo ? "is-demo" : ""}`}>
        <p>{isDemo ? "Local demo explanation" : "Optional Groq explanation"}</p>
        <p>{isDemo ? result.notice : "AI explanation generated by an open-weight model hosted through Groq."}</p>
      </div>
      <div className="ai-result-section">
        <h3>Educational explanation</h3>
        <p>{result.explanation.educationalSummary}</p>
      </div>
      {result.explanation.signalExplanations.length > 0 && (
        <div className="ai-result-section">
          <h3>How the local findings connect</h3>
          <ul className="ai-connection-list">
            {result.explanation.signalExplanations.map((item) => (
              <li key={item.signalId}>
                <p>{analysis.signals.find((signal) => signal.id === item.signalId)?.title ?? item.signalId}</p>
                <p>{item.explanation}</p>
              </li>
            ))}
          </ul>
        </div>
      )}
      <div className="ai-result-section">
        <h3>Suggested verification steps</h3>
        <ol className="ai-steps-list">
          {result.explanation.suggestedNextSteps.map((step, index) => (
            <li key={step}>
              <span aria-hidden="true">{index + 1}</span>
              <span>{step}</span>
            </li>
          ))}
        </ol>
      </div>
    </div>
  );
}

/** Renders the optional explanation action after, and subordinate to, the local report. */
export function AiExplanationPanel({ input, analysis, isAdminAuthenticated }: AiExplanationPanelProps) {
  const [result, setResult] = useState<AiExplanationResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generateExplanation = async () => {
    setIsLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch("/api/ai-explanation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        cache: "no-store",
        body: JSON.stringify(toAiExplanationInput(input)),
      });
      const payload: unknown = await response.json();
      const parsed = aiExplanationResponseSchema.safeParse(payload);

      if (parsed.success) {
        setResult(parsed.data);
      } else if (typeof payload === "object" && payload !== null && "error" in payload && typeof payload.error === "string") {
        setError(payload.error);
      } else {
        setError(LIVE_AI_UNAVAILABLE_MESSAGE);
      }
    } catch {
      setError(LIVE_AI_UNAVAILABLE_MESSAGE);
    } finally {
      setIsLoading(false);
    }
  };

  const actionLabel = isLoading
    ? (isAdminAuthenticated ? "Generating explanation…" : "Checking available explanation…")
    : (isAdminAuthenticated ? (error ? "Try again" : "Generate AI explanation") : "Check available explanation");

  return (
    <section className="ai-panel" aria-labelledby="ai-explanation-heading" aria-busy={isLoading}>
      <div className="ai-panel-heading">
        <div>
          <p className="eyebrow">Optional learning layer</p>
          <h2 id="ai-explanation-heading">Optional explanation</h2>
        </div>
        {isAdminAuthenticated && <p className="admin-session-badge">Admin session active</p>}
      </div>
      <p className="ai-primary-reminder">The local deterministic report above remains the canonical evidence. An AI explanation can help interpret its {analysis.signals.length} local finding{analysis.signals.length === 1 ? "" : "s"} for education, but cannot change its findings or make a safety verdict.</p>
      <p id="ai-explanation-consent" className="ai-consent-notice">
        {isAdminAuthenticated ? (
          <>By choosing <span>Generate AI explanation</span>, you consent to send the submitted email fields and server-recomputed local findings to Groq. AI explanation is generated by an open-weight model hosted through Groq.</>
        ) : (
          <>Public custom input never reaches Groq. Unchanged synthetic samples may show a local demo explanation; live Groq explanations require administrator access.</>
        )}
      </p>
      <button type="button" onClick={generateExplanation} disabled={isLoading} aria-describedby="ai-explanation-consent" className="button-secondary ai-action">
        {actionLabel}
      </button>
      {isLoading && <p className="ai-loading-status" role="status">{isAdminAuthenticated ? "Generating an optional explanation. Your local deterministic report remains available." : "Checking the available educational explanation. Your local deterministic report remains available."}</p>}
      {error && <p className="ai-error" role="alert">{error}</p>}
      {result && <ExplanationContent result={result} analysis={analysis} />}
    </section>
  );
}
